In [1]:
import numpy as np 

In [2]:
np.hstack((np.array([0,0.5]),np.outer(np.logspace(0,7,8),np.arange(1,10,0.5)).flatten()))

array([  0.00000000e+00,   5.00000000e-01,   1.00000000e+00,
         1.50000000e+00,   2.00000000e+00,   2.50000000e+00,
         3.00000000e+00,   3.50000000e+00,   4.00000000e+00,
         4.50000000e+00,   5.00000000e+00,   5.50000000e+00,
         6.00000000e+00,   6.50000000e+00,   7.00000000e+00,
         7.50000000e+00,   8.00000000e+00,   8.50000000e+00,
         9.00000000e+00,   9.50000000e+00,   1.00000000e+01,
         1.50000000e+01,   2.00000000e+01,   2.50000000e+01,
         3.00000000e+01,   3.50000000e+01,   4.00000000e+01,
         4.50000000e+01,   5.00000000e+01,   5.50000000e+01,
         6.00000000e+01,   6.50000000e+01,   7.00000000e+01,
         7.50000000e+01,   8.00000000e+01,   8.50000000e+01,
         9.00000000e+01,   9.50000000e+01,   1.00000000e+02,
         1.50000000e+02,   2.00000000e+02,   2.50000000e+02,
         3.00000000e+02,   3.50000000e+02,   4.00000000e+02,
         4.50000000e+02,   5.00000000e+02,   5.50000000e+02,
         6.00000000e+02,

In [3]:
min(3,4)

3

In [4]:
np.histogram(np.array([]))

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ]))